### ISSUE TITLE
Not compatible with the latest IntelliJ IDEA 2023.1

### ISSUE THREAD

**Issue by groundmuffin** [Tinhorn/freezed_intellij_live_templates#16] opened 2023-04-01 17:32 UTC
IntelliJ IDEA 2023.1 (Community Edition)
Build #IC-231.8109.175, built on March 28, 2023

**Comment by Tinhorn** [comment] 2023-04-04 23:28
Duplicate of #15 
Working on that

**Closed as completed by Tinhorn** 2023-04-04 23:28 UTC
